# Generated by Django 5.1.3 on 2026-09-18 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('agents_run', models.CharField(max_length=200)),
                ('verdict', models.CharField(max_length=50)),
                ('duration_ms', models.FloatField()),
                ('full_response', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True)),
                ('wave_height_m', models.FloatField(blank=True, null=True)),
                ('wave_period_s', models.FloatField(blank=True, null=True)),
                ('rain_chance_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MobileUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('hi', 'Hindi')], default='en', max_length=20)),
                ('boat_registration', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
