# Generated by Django 5.1.3 on 2026-09-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='verdict',
            field=models.CharField(choices=[('clear', 'Clear'), ('risk_flagged', 'Risk Flagged'), ('inconclusive', 'Inconclusive'), ('unknown', 'Unknown')], max_length=50),
        ),
    ]
