# Generated by Django 5.1.3 on 2026-09-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agentrun_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='pfz_zones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='route_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
